language: php

php:
    - 5.5
    - 5.4

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar update --dev --no-interaction

script:
    - php bin/markbench benchmark --profile=blank
    - php bin/markbench benchmark --profile=default
    - php bin/markbench benchmark --profile=github-sample
